const cargoModelData =
    [
        {
            "customerReferenceId": "AGOL-12-D",
            "customerName": "BOSCH",
            "shipper": "Shipper 1",
            "originAirport": "LAX Los Angeles Airport",
            "consignee": "Consignee 1",
            "destinationAirport": "JFK John F. Kennedy",
            "originInlandCarrier": "Origin Inland Carrier",
            "destinationInlandCarrier": "Destination Inland Carrier",
            "currentStatusName": "Cargo in Air Transit",
            "currentStatusId": "8",
            "agentAssigned": "Agent Assigned",
            "comments": "Commentsss",
        },
        {
            "customerReferenceId": "AGOL-28-F",
            "customerName": "Chevron",
            "shipper": "Shipper 2",
            "originAirport": "ORD Chicago",
            "consignee": "Consignee 2",
            "destinationAirport": "STL Seattle",
            "originInlandCarrier": "Origin Inland Carrier 2",
            "destinationInlandCarrier": "Destination Inland Carrier 2",
            "currentStatusName": "Dispatched for pickup",
            "currentStatusId": "1",
            "agentAssigned": "Agent Assigned 2",
            "comments": "Commentsss 4",
        },
        {
            "customerReferenceId": "AGOL-12-D",
            "customerName": "BOSCH",
            "shipper": "Shipper 1",
            "originAirport": "LAX Los Angeles Airport",
            "consignee": "Consignee 1",
            "destinationAirport": "JFK John F. Kennedy",
            "originInlandCarrier": "Origin Inland Carrier",
            "destinationInlandCarrier": "Destination Inland Carrier",
            "currentStatusName": "Cargo in Air Transit",
            "currentStatusId": "8",
            "agentAssigned": "Agent Assigned",
            "comments": "Commentsss",
        },
        {
            "customerReferenceId": "AGOL-28-F",
            "customerName": "Chevron",
            "shipper": "Shipper 2",
            "originAirport": "ORD Chicago",
            "consignee": "Consignee 2",
            "destinationAirport": "STL Seattle",
            "originInlandCarrier": "Origin Inland Carrier 2",
            "destinationInlandCarrier": "Destination Inland Carrier 2",
            "currentStatusName": "Dispatched for pickup",
            "currentStatusId": "1",
            "agentAssigned": "Agent Assigned 2",
            "comments": "Commentsss 4",
        },
        {
            "customerReferenceId": "AGOL-12-D",
            "customerName": "BOSCH",
            "shipper": "Shipper 1",
            "originAirport": "LAX Los Angeles Airport",
            "consignee": "Consignee 1",
            "destinationAirport": "JFK John F. Kennedy",
            "originInlandCarrier": "Origin Inland Carrier",
            "destinationInlandCarrier": "Destination Inland Carrier",
            "currentStatusName": "Cargo in Air Transit",
            "currentStatusId": "8",
            "agentAssigned": "Agent Assigned",
            "comments": "Commentsss",
        },
        {
            "customerReferenceId": "AGOL-28-F",
            "customerName": "Chevron",
            "shipper": "Shipper 2",
            "originAirport": "ORD Chicago",
            "consignee": "Consignee 2",
            "destinationAirport": "STL Seattle",
            "originInlandCarrier": "Origin Inland Carrier 2",
            "destinationInlandCarrier": "Destination Inland Carrier 2",
            "currentStatusName": "Dispatched for pickup",
            "currentStatusId": "1",
            "agentAssigned": "Agent Assigned 2",
            "comments": "Commentsss 4",
        },
        {
            "customerReferenceId": "AGOL-12-D",
            "customerName": "BOSCH",
            "shipper": "Shipper 1",
            "originAirport": "LAX Los Angeles Airport",
            "consignee": "Consignee 1",
            "destinationAirport": "JFK John F. Kennedy",
            "originInlandCarrier": "Origin Inland Carrier",
            "destinationInlandCarrier": "Destination Inland Carrier",
            "currentStatusName": "Cargo in Air Transit",
            "currentStatusId": "8",
            "agentAssigned": "Agent Assigned",
            "comments": "Commentsss",
        },
        {
            "customerReferenceId": "AGOL-28-F",
            "customerName": "Chevron",
            "shipper": "Shipper 2",
            "originAirport": "ORD Chicago",
            "consignee": "Consignee 2",
            "destinationAirport": "STL Seattle",
            "originInlandCarrier": "Origin Inland Carrier 2",
            "destinationInlandCarrier": "Destination Inland Carrier 2",
            "currentStatusName": "Dispatched for pickup",
            "currentStatusId": "1",
            "agentAssigned": "Agent Assigned 2",
            "comments": "Commentsss 4",
        },
        {
            "customerReferenceId": "AGOL-12-D",
            "customerName": "BOSCH",
            "shipper": "Shipper 1",
            "originAirport": "LAX Los Angeles Airport",
            "consignee": "Consignee 1",
            "destinationAirport": "JFK John F. Kennedy",
            "originInlandCarrier": "Origin Inland Carrier",
            "destinationInlandCarrier": "Destination Inland Carrier",
            "currentStatusName": "Cargo in Air Transit",
            "currentStatusId": "8",
            "agentAssigned": "Agent Assigned",
            "comments": "Commentsss",
        },
        {
            "customerReferenceId": "AGOL-28-F",
            "customerName": "Chevron",
            "shipper": "Shipper 2",
            "originAirport": "ORD Chicago",
            "consignee": "Consignee 2",
            "destinationAirport": "STL Seattle",
            "originInlandCarrier": "Origin Inland Carrier 2",
            "destinationInlandCarrier": "Destination Inland Carrier 2",
            "currentStatusName": "Dispatched for pickup",
            "currentStatusId": "1",
            "agentAssigned": "Agent Assigned 2",
            "comments": "Commentsss 4",
        }
    ]


export { cargoModelData }