export enum EntityTypes {
    DTA_Merchant = 1,
    DTA_Processor = 2,
    DTA_BusinessGroup = 3,
    DTA_Bank = 4,
    DTA_Terminal = 5,
    DTA_Agent = 6,
    DTA_Partner = 7,
    DTA_Network = 8,
    DTA_Pocket = 9,
    DTA_Provision = 10,
    DTA_Client = 11,
    DTA_ApplicationMerchant = 13,
    DTA_Transaction = 14,
    DTA_TerminalBin = 15,
    DTA_Bin = 16,
    DTA_ChargeBack = 17,
}